### ISSUE TITLE
After running demo app, tests print EnvironmentMismatchError warning

### ISSUE THREAD

**Issue by mattbrictson** [bootstrap-ruby/bootstrap_form#402] opened 2018-01-24 03:12 UTC
If I run the demo app using these steps as listed in CONTRIBUTING.md:

```
cd demo
rake db:schema:load
rails server
```

And then later I run the tests, I then see

```
$ rake
rails aborted!
ActiveRecord::EnvironmentMismatchError: You are attempting to modify a database that was last run in `development` environment.
You are running in `test` environment. If you are sure you want to continue, first set the environment using:

        bin/rails db:environment:set RAILS_ENV=test

bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:test:load => db:test:purge => db:check_protected_environments
(See full trace by running task with --trace)
```

The tests otherwise continue to run normally, without errors.

I have gotten the error go away by doing this:

```
rm -rf demo/db/*.sqlite3
```

But that doesn't seem ideal. The tests should just work without scary warnings.

**Comment by lcreid** [comment] 2018-01-25 19:03
@mattbrictson I pulled this into my development environment, and now all tests cause an error. I've pasted one stack trace below. I can make the errors go away by running my tests like this:

```
RAILS_ENV=test bundle exec rake test
```

but then I get the warning messages you were trying to get rid of. I will try to figure out what I'm doing wrong, but any hints would be appreciated.

Stack trace (each test case triggers its own):

```
Error:
BootstrapRadioButtonTest#test_collection_radio_buttons_renders_value_defined_by_lambda_correctly:
ActiveRecord::StatementInvalid: Could not find table 'users'
    activerecord (5.1.4) lib/active_record/connection_adapters/sqlite3_adapter.rb:417:in `table_structure'
    activerecord (5.1.4) lib/active_record/connection_adapters/abstract_adapter.rb:166:in `columns'
    activerecord (5.1.4) lib/active_record/connection_adapters/schema_cache.rb:67:in `columns'
    activerecord (5.1.4) lib/active_record/connection_adapters/schema_cache.rb:73:in `columns_hash'
    activerecord (5.1.4) lib/active_record/model_schema.rb:471:in `load_schema!'
    activerecord (5.1.4) lib/active_record/attributes.rb:233:in `load_schema!'
    activerecord (5.1.4) lib/active_record/attribute_decorators.rb:50:in `load_schema!'
    activerecord (5.1.4) lib/active_record/model_schema.rb:464:in `block in load_schema'
    /usr/local/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
    activerecord (5.1.4) lib/active_record/model_schema.rb:461:in `load_schema'
    activerecord (5.1.4) lib/active_record/model_schema.rb:353:in `attribute_types'
    activerecord (5.1.4) lib/active_record/attribute_methods.rb:179:in `has_attribute?'
    activerecord (5.1.4) lib/active_record/inheritance.rb:55:in `new'
    /vagrant/test/test_helper.rb:15:in `setup_test_fixture'
    activesupport (5.1.4) lib/active_support/callbacks.rb:413:in `block in make_lambda'
    activesupport (5.1.4) lib/active_support/callbacks.rb:197:in `block (2 levels) in halting'
    activesupport (5.1.4) lib/active_support/callbacks.rb:601:in `block (2 levels) in default_terminator'
    activesupport (5.1.4) lib/active_support/callbacks.rb:600:in `catch'
    activesupport (5.1.4) lib/active_support/callbacks.rb:600:in `block in default_terminator'
    activesupport (5.1.4) lib/active_support/callbacks.rb:198:in `block in halting'
    activesupport (5.1.4) lib/active_support/callbacks.rb:507:in `block in invoke_before'
    activesupport (5.1.4) lib/active_support/callbacks.rb:507:in `each'
    activesupport (5.1.4) lib/active_support/callbacks.rb:507:in `invoke_before'
    activesupport (5.1.4) lib/active_support/callbacks.rb:130:in `run_callbacks'
    activesupport (5.1.4) lib/active_support/testing/setup_and_teardown.rb:41:in `before_setup'
    activerecord (5.1.4) lib/active_record/fixtures.rb:852:in `before_setup'
    minitest (5.10.3) lib/minitest/test.rb:105:in `block (3 levels) in run'
    minitest (5.10.3) lib/minitest/test.rb:204:in `capture_exceptions'
    minitest (5.10.3) lib/minitest/test.rb:104:in `block (2 levels) in run'
    minitest (5.10.3) lib/minitest/test.rb:255:in `time_it'
    minitest (5.10.3) lib/minitest/test.rb:103:in `block in run'
    minitest (5.10.3) lib/minitest.rb:350:in `on_signal'
    minitest (5.10.3) lib/minitest/test.rb:275:in `with_info_handler'
    minitest (5.10.3) lib/minitest/test.rb:102:in `run'
    minitest (5.10.3) lib/minitest.rb:839:in `run_one_method'
    minitest (5.10.3) lib/minitest.rb:324:in `run_one_method'
    minitest (5.10.3) lib/minitest.rb:311:in `block (2 levels) in run'
    minitest (5.10.3) lib/minitest.rb:310:in `each'
    minitest (5.10.3) lib/minitest.rb:310:in `block in run'
    minitest (5.10.3) lib/minitest.rb:350:in `on_signal'
    minitest (5.10.3) lib/minitest.rb:337:in `with_info_handler'
    minitest (5.10.3) lib/minitest.rb:309:in `run'
    railties (5.1.4) lib/rails/test_unit/line_filtering.rb:9:in `run'
    minitest (5.10.3) lib/minitest.rb:159:in `block in __run'
    minitest (5.10.3) lib/minitest.rb:159:in `map'
    minitest (5.10.3) lib/minitest.rb:159:in `__run'
    minitest (5.10.3) lib/minitest.rb:136:in `run'
    minitest (5.10.3) lib/minitest.rb:63:in `block in autorun'
```

**Comment by lcreid** [comment] 2018-01-25 22:58
I wonder if the original issue of the annying message was caused by https://github.com/rails/rails/issues/26731? I checked my test database, and it indeed had "development" in the `ar_internal_metadata` table. I manually changed it by:
```
cd demo/db
sqlite3 test.sqlite3
update ar_internal_metadata set value = 'test';
.exit
cd -
```
And the annoying message went away.

However, the tests still fail unless I specify:
```
RAILS_ENV=test bundle exec rake test
```

**Comment by lcreid** [comment] 2018-01-25 23:06
So it looks like the fix to the issue referenced above was backported to 5.0 and 5.1 in October, and the current versions of 5.0 and 5.1 that we're using were released in September (http://weblog.rubyonrails.org/2017/9/7/Rails-5-1-4-and-5-0-6-released/). 

I can't say for sure why I didn't notice this before. It looks like the database location has changed. Perhaps the database I was using before was old enough that it didn't have the bug, so it only appeared when the new database was created.

**Closed** 2018-01-26 00:00 UTC
Labels: chore

**Comment by mattbrictson** [comment] 2018-01-26 03:51
@lcreid thanks for looking into this. I'll also keep an eye on whether any problems like this resurface.

**Comment by lcreid** [comment] 2018-01-26 03:55
My pleasure. It was the darndest thing. I could make the problem go away and come back all afternoon. I went to do one last test when I was preparing additional instructions for the work-arounds, and suddenly I couldn't make it happen any more. :-)

**Comment by lancecarlson** [comment] 2018-04-30 20:33
@lcreid This happened to me on a fresh fork. Still having trouble getting it to recognize a users table.

**Comment by mattbrictson** [comment] 2018-05-30 20:48
@lancecarlson can you test the branch in PR #464 to see if it fixes the problem for you on a fresh clone?
