### ISSUE TITLE
Can't disable number_field

### ISSUE THREAD

**Issue by itmart** [bootstrap-ruby/bootstrap_form#688] opened 2023-06-21 20:57 UTC
```
f.number_field :earned_points, disabled: true
```

The field will not be disabled. Also tried this syntax:

```
f.number_field :earned_points, {}, disabled: true
```
But that gives me this error:
```
unknown keyword: :disabled
```

**Comment by donv** [comment] 2023-08-17 07:08
Hi @itmart !

I just committed some changes in the builder.  Could you test your app with the latest main branch?

**Comment by donv** [comment] 2023-08-28 10:12
Hi @itmart !

I am closing this since I cannot reproduce the problem.  I have added a section for disabled fields in the README.  Please reopen if this still does not work for you.

https://github.com/bootstrap-ruby/bootstrap_form#disabled-fields

**Closed by donv** 2023-08-28 10:12 UTC
