### ISSUE TITLE
Any reason why field errors remove help text?

### ISSUE THREAD

**Issue by GBH** [bootstrap-ruby/bootstrap_form#419] opened 2018-01-31 20:07 UTC
It's not that they share same feedback container either. Maybe they did in previous bootstrap version?

Right now one is `invalid-feedback` and other is `text-muted` tag. I think both should show up.

**Comment by mattbrictson** [comment] 2018-01-31 22:28
This is a duplicate of #284. Let's move the discussion there.

**Closed by mattbrictson** 2018-01-31 22:28 UTC
